### ISSUE TITLE
Redesign "new ticket" and "ticket assigned" notifications

### ISSUE THREAD

**Issue by tomwassing** [TicketVise/ticketvise#236]
Johannes only left assigned emails on. He never got emails when a new ticket was created, even though new tickets are automatically assigned to him

- Improve notification descriptions
- New ticket notification must occur when a new unassigned ticket has been created in inbox
- Ticket assigned notification should occur whenever a ticket has been assigned to a users (even if newly created).

**Comment by rubenjonk** [comment]
-[ ] Are both the TicketAssigned and NewTickets notifications necessary?
- [] Nothing happens when the assignee of a ticket changes.
-[ ] Students can see the TicketAssigned and Reminder option in account
