### ISSUE TITLE
Downloaded attachments lose their file extension

### ISSUE THREAD

**Issue by FolkertVanVerseveld** [TicketVise/ticketvise#314]
On uva.ticketvise.com the following scenario is executed given a student A and teaching assistant B:

* Student `A` opens a new ticket and attaches file `C.def` with extension `def`.
* Teaching assistant `B` downloads `C.def`, but the file is named `C` and missing the file extension.

Problem: any downloaded attachment file is missing its file extension.
Reproducable for any files that have a file extension.

**Comment by IvandeWolf** [comment]
Tested it:
- Locally
- In the test course in the test Canvas environment (which is the dev environment)

And it seems to be fixed somewhere along the line. So for now I will close this issue.

**Comment by IvandeWolf** [comment]
It's still an issue as I've encountered it myself so we will need to look further into this.
